build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Seatable"
  org.opencontainers.image.description: "Seatable - A spreadsheet-like database solution"
  org.opencontainers.image.source: "https://github.com/d-shmt/ha-addon_seatable"
  org.opencontainers.image.licenses: "Apache License 2.0"